/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh.atm;

/**
 *
 * @author dhenarraerine
 */
public class Cek extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
     int tabungan = 0;
     
     public Cek(int tabungan) {
        this.tabungan = tabungan;
        initComponents();
        jlSaldo.setText("Saldo = Rp" + tabungan);
        initComponents();
    }
    public Cek() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbCek = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        jlSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("ATM BANK JATIM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 300, 60);

        jbCek.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbCek.setText("Cek Saldo");
        jbCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCekActionPerformed(evt);
            }
        });
        getContentPane().add(jbCek);
        jbCek.setBounds(20, 60, 310, 30);

        jbKembali.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbKembali.setText("Kembali");
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbKembali);
        jbKembali.setBounds(180, 320, 150, 40);

        jbKeluar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbKeluar);
        jbKeluar.setBounds(20, 320, 150, 40);
        getContentPane().add(jlSaldo);
        jlSaldo.setBounds(20, 110, 310, 50);

        setBounds(0, 0, 367, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCekActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbCekActionPerformed

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbKembaliActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCek;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbKembali;
    private javax.swing.JLabel jlSaldo;
    // End of variables declaration//GEN-END:variables
}
