/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh.atm;

/**
 *
 * @author dhenarraerine
 */
import javax.swing.JOptionPane;
public class Tarik extends javax.swing.JFrame {
    int tabungan = 0;

    /**
     * Creates new form Main
     */
    public Tarik(int tabungan) {
        this.tabungan = tabungan;
        initComponents();
    }
    public Tarik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbTarik = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        jtf1 = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        nol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("ATM BANK JATIM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 300, 60);

        jbTarik.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbTarik.setText("Tarik");
        jbTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarikActionPerformed(evt);
            }
        });
        getContentPane().add(jbTarik);
        jbTarik.setBounds(20, 60, 310, 30);

        jbKembali.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbKembali.setText("Kembali");
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbKembali);
        jbKembali.setBounds(180, 330, 150, 40);

        jbKeluar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbKeluar);
        jbKeluar.setBounds(20, 330, 150, 40);

        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf1);
        jtf1.setBounds(20, 100, 310, 40);

        reset.setText("reset");
        getContentPane().add(reset);
        reset.setBounds(230, 270, 60, 50);

        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu);
        satu.setBounds(20, 150, 60, 50);

        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua);
        dua.setBounds(90, 150, 60, 50);

        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga);
        tiga.setBounds(160, 150, 60, 50);

        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat);
        empat.setBounds(20, 210, 60, 50);

        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima);
        lima.setBounds(90, 210, 60, 50);

        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam);
        enam.setBounds(160, 210, 60, 50);

        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh);
        tujuh.setBounds(20, 270, 60, 50);

        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan);
        delapan.setBounds(90, 270, 60, 50);

        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan);
        sembilan.setBounds(160, 270, 60, 50);

        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol);
        nol.setBounds(230, 210, 60, 50);

        setBounds(0, 0, 367, 424);
    }// </editor-fold>//GEN-END:initComponents
       String input = "";
    private void jbTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarikActionPerformed
        // TODO add your handling code here:
        int tarik = Integer.parseInt(jtf1.getText());
        if (tarik % 100 != 0)
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima uang koin\nSilahkan ulangi lagi", "Transaksi Gagal", 0);
        else if (tarik > tabungan)
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi\nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
        else if (tarik < 50000)
            JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan tunai adalah Rp50.000,00", "Transaksi Gagal", 0);
        else {
            tabungan -= tarik;
            JOptionPane.showMessageDialog(null, "Saldo anda saat ini sebesar : " + tabungan);
            if (tabungan <= 50000)
                JOptionPane.showMessageDialog(null, "Saldo minimal harus Rp50.000,00, segera lakukan penyetoran untuk menghindari penutupan akun", "CAUTION", 2);
        }
    }//GEN-LAST:event_jbTarikActionPerformed

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbKembaliActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbKeluarActionPerformed

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1ActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        input += "1";
        jtf1.setText(input);
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        input += "2";
        jtf1.setText(input);
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        input += "3";
        jtf1.setText(input);
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        input += "4";
        jtf1.setText(input);
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        input += "5";
        jtf1.setText(input);
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        input += "6";
        jtf1.setText(input);
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        input += "7";
        jtf1.setText(input);
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        input += "8";
        jtf1.setText(input);
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        input += "9";
        jtf1.setText(input);
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
        input += "0";
        jtf1.setText(input);
    }//GEN-LAST:event_nolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbKembali;
    private javax.swing.JButton jbTarik;
    private javax.swing.JTextField jtf1;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton reset;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
